# Generated by Django 3.2.24 on 2025-02-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('bp', models.CharField(max_length=100)),
                ('cholestrol', models.CharField(max_length=100)),
                ('sugar', models.CharField(max_length=100)),
                ('healthcondition', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('dietplan', models.CharField(max_length=100)),
                ('excersiseplan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diet_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=1, max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(max_length=100)),
                ('Dietplan', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=100)),
                ('Obicity', models.CharField(max_length=100)),
                ('Bloodpressure', models.CharField(max_length=100)),
                ('Diabetes', models.CharField(max_length=100)),
                ('Cholestrol', models.CharField(max_length=100)),
                ('Alcoholabuse', models.CharField(max_length=100)),
                ('Druguse', models.CharField(max_length=100)),
                ('Smoking', models.CharField(max_length=100)),
                ('Headaches', models.CharField(max_length=100)),
                ('Asthma', models.CharField(max_length=100)),
                ('Heartproblem', models.CharField(max_length=100)),
                ('Cancer', models.CharField(max_length=100)),
                ('Stroke', models.CharField(max_length=100)),
                ('Kidney', models.CharField(max_length=100)),
                ('Liver', models.CharField(max_length=100)),
                ('Depression', models.CharField(max_length=100)),
                ('Allergies', models.CharField(max_length=100)),
                ('Arthritis', models.CharField(max_length=100)),
                ('Pregnancy', models.CharField(max_length=100)),
                ('bmi', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('idproof', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Bloodtype', models.CharField(max_length=100)),
                ('Photo', models.FileField(upload_to='')),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('District', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Workassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('EXPERT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.experts')),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
                ('alert', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('gram', models.IntegerField()),
                ('callorie', models.IntegerField()),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='experts',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.CreateModel(
            name='Expertfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=400)),
                ('rating', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('EXPERT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.experts')),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=400)),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=2000)),
                ('FROMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='myapp.login')),
                ('TOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='myapp.login')),
            ],
        ),
    ]
