# Generated by Django 3.2.24 on 2025-02-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='gram',
            field=models.FloatField(),
        ),
    ]
