# Generated by Django 5.1.7 on 2025-12-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_food_gram'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diet_chart',
            table='mental_app_paymentaccess',
        ),
        migrations.CreateModel(
            name='PaymentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=120, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='myapp.login')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='myapp.login')),
            ],
        ),
    ]
