# Generated by Django 5.1.7 on 2025-12-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_diet_chart_table_paymentaccess'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diet_chart',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentaccess',
            table='mental_app_paymentaccess',
        ),
    ]
