# Generated by Django 5.1.7 on 2026-03-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_diet_chart_table_alter_paymentaccess_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='msg_type',
            field=models.CharField(default='text', max_length=10),
        ),
    ]
